language: python
version:
    - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

script:
  - docker-compose run app sh -c "python manage.py test && flake8"



