language: python
version:
    - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose run app sh -c "sudo apt-get update"
  - docker-compose run app sh -c "sudo apt-get install python3.6"
  - docker-compose run app sh -c "python --version"

script:
  - docker-compose run app sh -c "python manage.py test && flake8"



